"""Change content column from VARCHAR(100) to TEXT in universities_majors

Revision ID: 211b2d28e34a
Revises: b0bbc1761d77
Create Date: 2026-05-10 10:03:09.435018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '211b2d28e34a'
down_revision: Union[str, Sequence[str], None] = 'b0bbc1761d77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_messages', 'role2')
    op.alter_column('universities_majors', 'content',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('universities_majors', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.add_column('conversation_messages', sa.Column('role2', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
