"""Create riasec_sessions and conversation_messages tables

Revision ID: 76daa3ab3a06
Revises: 
Create Date: 2026-05-10 07:42:11.923721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76daa3ab3a06'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('riasec_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=True),
    sa.Column('current_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('groups_asked', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_riasec_sessions_session_id'), 'riasec_sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_riasec_sessions_student_id'), 'riasec_sessions', ['student_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('riasec_target', sa.String(length=3), nullable=True),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['riasec_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_conversation_messages_message_id'), 'conversation_messages', ['message_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_session_id'), 'conversation_messages', ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_conversation_messages_session_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_message_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_riasec_sessions_student_id'), table_name='riasec_sessions')
    op.drop_index(op.f('ix_riasec_sessions_session_id'), table_name='riasec_sessions')
    op.drop_table('riasec_sessions')
    # ### end Alembic commands ###
