"""init_riasec_service

Revision ID: 7b387dfe99e5
Revises: 
Create Date: 2026-05-14 04:40:21.700949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b387dfe99e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('riasec_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('min_steps', sa.Integer(), nullable=False),
    sa.Column('max_steps', sa.Integer(), nullable=False),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('entropy', sa.Float(), nullable=False),
    sa.Column('current_focus_groups', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('riasec_code', sa.String(length=10), nullable=True),
    sa.Column('termination_reason', sa.String(length=255), nullable=True),
    sa.Column('final_summary', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('session_id'),
    schema='riasec'
    )
    op.create_index(op.f('ix_riasec_riasec_sessions_riasec_code'), 'riasec_sessions', ['riasec_code'], unique=False, schema='riasec')
    op.create_index(op.f('ix_riasec_riasec_sessions_status'), 'riasec_sessions', ['status'], unique=False, schema='riasec')
    op.create_index(op.f('ix_riasec_riasec_sessions_student_id'), 'riasec_sessions', ['student_id'], unique=False, schema='riasec')
    op.create_table('conversation_messages',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('riasec_signal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['riasec.riasec_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id'),
    schema='riasec'
    )
    op.create_index(op.f('ix_riasec_conversation_messages_role'), 'conversation_messages', ['role'], unique=False, schema='riasec')
    op.create_index(op.f('ix_riasec_conversation_messages_session_id'), 'conversation_messages', ['session_id'], unique=False, schema='riasec')
    op.create_table('digital_competency_profiles',
    sa.Column('dcp_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('riasec_code', sa.String(length=10), nullable=False),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('career_groups', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('digital_competencies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_majors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['riasec.riasec_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dcp_id'),
    schema='riasec'
    )
    op.create_index(op.f('ix_riasec_digital_competency_profiles_riasec_code'), 'digital_competency_profiles', ['riasec_code'], unique=False, schema='riasec')
    op.create_index(op.f('ix_riasec_digital_competency_profiles_session_id'), 'digital_competency_profiles', ['session_id'], unique=False, schema='riasec')
    op.create_index(op.f('ix_riasec_digital_competency_profiles_student_id'), 'digital_competency_profiles', ['student_id'], unique=False, schema='riasec')
    op.create_table('riasec_score_snapshots',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('entropy', sa.Float(), nullable=False),
    sa.Column('dominant_code', sa.String(length=10), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['riasec.conversation_messages.message_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['riasec.riasec_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id'),
    schema='riasec'
    )
    op.create_index(op.f('ix_riasec_riasec_score_snapshots_message_id'), 'riasec_score_snapshots', ['message_id'], unique=False, schema='riasec')
    op.create_index(op.f('ix_riasec_riasec_score_snapshots_session_id'), 'riasec_score_snapshots', ['session_id'], unique=False, schema='riasec')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_riasec_riasec_score_snapshots_session_id'), table_name='riasec_score_snapshots', schema='riasec')
    op.drop_index(op.f('ix_riasec_riasec_score_snapshots_message_id'), table_name='riasec_score_snapshots', schema='riasec')
    op.drop_table('riasec_score_snapshots', schema='riasec')
    op.drop_index(op.f('ix_riasec_digital_competency_profiles_student_id'), table_name='digital_competency_profiles', schema='riasec')
    op.drop_index(op.f('ix_riasec_digital_competency_profiles_session_id'), table_name='digital_competency_profiles', schema='riasec')
    op.drop_index(op.f('ix_riasec_digital_competency_profiles_riasec_code'), table_name='digital_competency_profiles', schema='riasec')
    op.drop_table('digital_competency_profiles', schema='riasec')
    op.drop_index(op.f('ix_riasec_conversation_messages_session_id'), table_name='conversation_messages', schema='riasec')
    op.drop_index(op.f('ix_riasec_conversation_messages_role'), table_name='conversation_messages', schema='riasec')
    op.drop_table('conversation_messages', schema='riasec')
    op.drop_index(op.f('ix_riasec_riasec_sessions_student_id'), table_name='riasec_sessions', schema='riasec')
    op.drop_index(op.f('ix_riasec_riasec_sessions_status'), table_name='riasec_sessions', schema='riasec')
    op.drop_index(op.f('ix_riasec_riasec_sessions_riasec_code'), table_name='riasec_sessions', schema='riasec')
    op.drop_table('riasec_sessions', schema='riasec')
    # ### end Alembic commands ###
