"""Add universities_majors table and update conversation_messages

Revision ID: b0bbc1761d77
Revises: eb0fe72137d9
Create Date: 2026-05-10 09:57:47.722693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0bbc1761d77'
down_revision: Union[str, Sequence[str], None] = 'eb0fe72137d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universities_majors',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('student_id', sa.String(length=200), nullable=False),
    sa.Column('logo', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('name_universities', sa.String(length=20), nullable=False),
    sa.Column('name_majors', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_universities_majors_id'), 'universities_majors', ['id'], unique=False)
    op.create_index(op.f('ix_universities_majors_student_id'), 'universities_majors', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_universities_majors_student_id'), table_name='universities_majors')
    op.drop_index(op.f('ix_universities_majors_id'), table_name='universities_majors')
    op.drop_table('universities_majors')
    # ### end Alembic commands ###
