"""Change id column to UUID in universities_majors

Revision ID: dbf6cf97a967
Revises: 211b2d28e34a
Create Date: 2026-05-10 10:07:45.932902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbf6cf97a967'
down_revision: Union[str, Sequence[str], None] = '211b2d28e34a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('universities_majors', 'id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='id::uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('universities_majors', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               postgresql_using='id::varchar')
    # ### end Alembic commands ###
