"""customs

Revision ID: eb0fe72137d9
Revises: 76daa3ab3a06
Create Date: 2026-05-10 08:24:50.186515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb0fe72137d9'
down_revision: Union[str, Sequence[str], None] = '76daa3ab3a06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_messages', sa.Column('role2', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_messages', 'role2')
    # ### end Alembic commands ###
