"""add_vector_table

Revision ID: 5c3cd6e7aafd
Revises: 
Create Date: 2026-05-16 06:21:09.243031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# pyrefly: ignore [missing-import]
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '5c3cd6e7aafd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('chunk_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='rag'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_chunks', schema='rag')
    # ### end Alembic commands ###
