"""init_rag_service

Revision ID: 8b3a9a556b47
Revises: 
Create Date: 2026-05-18 13:18:45.176132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '8b3a9a556b47'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_path', sa.String(length=500), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('university_name', sa.String(length=255), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash', name='uq_document_chunks_content_hash'),
    schema='rag'
    )
    op.create_index(op.f('ix_rag_document_chunks_content_hash'), 'document_chunks', ['content_hash'], unique=False, schema='rag')
    op.create_index(op.f('ix_rag_document_chunks_region'), 'document_chunks', ['region'], unique=False, schema='rag')
    op.create_index(op.f('ix_rag_document_chunks_source_name'), 'document_chunks', ['source_name'], unique=False, schema='rag')
    op.create_index(op.f('ix_rag_document_chunks_source_path'), 'document_chunks', ['source_path'], unique=False, schema='rag')
    op.create_index(op.f('ix_rag_document_chunks_university_name'), 'document_chunks', ['university_name'], unique=False, schema='rag')
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_rag_document_chunks_embedding_hnsw "
        "ON rag.document_chunks "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS rag.ix_rag_document_chunks_embedding_hnsw")
    op.drop_index(op.f('ix_rag_document_chunks_university_name'), table_name='document_chunks', schema='rag')
    op.drop_index(op.f('ix_rag_document_chunks_source_path'), table_name='document_chunks', schema='rag')
    op.drop_index(op.f('ix_rag_document_chunks_source_name'), table_name='document_chunks', schema='rag')
    op.drop_index(op.f('ix_rag_document_chunks_region'), table_name='document_chunks', schema='rag')
    op.drop_index(op.f('ix_rag_document_chunks_content_hash'), table_name='document_chunks', schema='rag')
    op.drop_table('document_chunks', schema='rag')
    # ### end Alembic commands ###
