"""init_profile_service

Revision ID: 61cbdf9d7dd8
Revises: 
Create Date: 2026-05-14 02:59:51.108441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61cbdf9d7dd8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=False),
    sa.Column('area_code', sa.String(length=5), nullable=False),
    sa.Column('priority_group', sa.String(length=10), nullable=True),
    sa.Column('target_province', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('student_id'),
    schema='profile'
    )
    op.create_index(op.f('ix_profile_students_email'), 'students', ['email'], unique=True, schema='profile')
    op.create_table('student_academic_records',
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('grade_10_avg', sa.Float(), nullable=True),
    sa.Column('grade_11_avg', sa.Float(), nullable=True),
    sa.Column('grade_12_avg', sa.Float(), nullable=True),
    sa.Column('exam_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exam_type', sa.String(length=20), nullable=False),
    sa.Column('exam_year', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['profile.students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id'),
    schema='profile'
    )
    op.create_index(op.f('ix_profile_student_academic_records_student_id'), 'student_academic_records', ['student_id'], unique=True, schema='profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_student_academic_records_student_id'), table_name='student_academic_records', schema='profile')
    op.drop_table('student_academic_records', schema='profile')
    op.drop_index(op.f('ix_profile_students_email'), table_name='students', schema='profile')
    op.drop_table('students', schema='profile')
    # ### end Alembic commands ###
