"""update_exam_2025_format

Revision ID: e594832aa86e
Revises: 61cbdf9d7dd8
Create Date: 2026-05-16 08:32:14.373807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e594832aa86e'
down_revision: Union[str, Sequence[str], None] = '61cbdf9d7dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_academic_records', sa.Column('score_math', sa.Float(), nullable=True), schema='profile')
    op.add_column('student_academic_records', sa.Column('score_literature', sa.Float(), nullable=True), schema='profile')
    op.add_column('student_academic_records', sa.Column('optional_subject_1', sa.String(length=50), nullable=True), schema='profile')
    op.add_column('student_academic_records', sa.Column('score_optional_1', sa.Float(), nullable=True), schema='profile')
    op.add_column('student_academic_records', sa.Column('optional_subject_2', sa.String(length=50), nullable=True), schema='profile')
    op.add_column('student_academic_records', sa.Column('score_optional_2', sa.Float(), nullable=True), schema='profile')
    op.add_column('student_academic_records', sa.Column('ielts_score', sa.Float(), nullable=True), schema='profile')
    op.add_column('student_academic_records', sa.Column('toeic_score', sa.Integer(), nullable=True), schema='profile')
    op.drop_column('student_academic_records', 'exam_type', schema='profile')
    op.drop_column('student_academic_records', 'grade_12_avg', schema='profile')
    op.drop_column('student_academic_records', 'grade_11_avg', schema='profile')
    op.drop_column('student_academic_records', 'grade_10_avg', schema='profile')
    op.drop_column('student_academic_records', 'exam_scores', schema='profile')
    op.add_column('students', sa.Column('target_country', sa.String(length=100), nullable=True), schema='profile')
    op.add_column('students', sa.Column('target_budget', sa.Integer(), nullable=True), schema='profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'target_budget', schema='profile')
    op.drop_column('students', 'target_country', schema='profile')
    op.add_column('student_academic_records', sa.Column('exam_scores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False), schema='profile')
    op.add_column('student_academic_records', sa.Column('grade_10_avg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True), schema='profile')
    op.add_column('student_academic_records', sa.Column('grade_11_avg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True), schema='profile')
    op.add_column('student_academic_records', sa.Column('grade_12_avg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True), schema='profile')
    op.add_column('student_academic_records', sa.Column('exam_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False), schema='profile')
    op.drop_column('student_academic_records', 'toeic_score', schema='profile')
    op.drop_column('student_academic_records', 'ielts_score', schema='profile')
    op.drop_column('student_academic_records', 'score_optional_2', schema='profile')
    op.drop_column('student_academic_records', 'optional_subject_2', schema='profile')
    op.drop_column('student_academic_records', 'score_optional_1', schema='profile')
    op.drop_column('student_academic_records', 'optional_subject_1', schema='profile')
    op.drop_column('student_academic_records', 'score_literature', schema='profile')
    op.drop_column('student_academic_records', 'score_math', schema='profile')
    # ### end Alembic commands ###
