"""custom column to users

Revision ID: f46b5d5ef154
Revises: fca4b06d499a
Create Date: 2026-05-10 07:45:09.715017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f46b5d5ef154'
down_revision: Union[str, Sequence[str], None] = 'fca4b06d499a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment='Thời điểm tạo user',
               existing_comment='Thời điểm đăng ký',
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Thời điểm cập nhật user',
               existing_comment='Lần cập nhật học lực gần nhất',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('users_session_id_key', 'users', type_='unique')
    op.drop_column('users', 'dcp_created_at')
    op.drop_column('users', 'session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True, comment='Phiên tạo ra DCP này'))
    op.add_column('users', sa.Column('dcp_created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Thời điểm tạo DCP'))
    op.create_unique_constraint('users_session_id_key', 'users', ['session_id'])
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Lần cập nhật học lực gần nhất',
               existing_comment='Thời điểm cập nhật user',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='Thời điểm đăng ký',
               existing_comment='Thời điểm tạo user',
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
