"""add email column to users

Revision ID: fca4b06d499a
Revises: a0c9a6383086
Create Date: 2026-05-10 07:41:27.884001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fca4b06d499a'
down_revision: Union[str, Sequence[str], None] = 'a0c9a6383086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('student_id', sa.UUID(), nullable=False, comment='Khóa chính định danh học sinh'))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Mật khẩu đã hash (bcrypt)'))
    op.add_column('users', sa.Column('dob', sa.Date(), nullable=True, comment='Ngày sinh'))
    op.add_column('users', sa.Column('province', sa.String(length=100), nullable=False, comment='Tỉnh/thành phố hiện tại'))
    op.add_column('users', sa.Column('area_code', sa.String(length=5), nullable=False, comment='Mã khu vực ưu tiên (KV1/KV2/KV3)'))
    op.add_column('users', sa.Column('priority_group', sa.String(length=10), nullable=True, comment='Đối tượng ưu tiên (01–07)'))
    op.add_column('users', sa.Column('target_province', sa.String(length=100), nullable=True, comment='Khu vực mong muốn học'))
    op.add_column('users', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Thời điểm đăng ký'))
    op.add_column('users', sa.Column('grade_10_avg', sa.Float(), nullable=True, comment='Điểm TB lớp 10'))
    op.add_column('users', sa.Column('grade_11_avg', sa.Float(), nullable=True, comment='Điểm TB lớp 11'))
    op.add_column('users', sa.Column('grade_12_avg', sa.Float(), nullable=True, comment='Điểm TB lớp 12'))
    op.add_column('users', sa.Column('exam_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Điểm thi theo môn: {toan, van, anh, ly, hoa, sinh...}'))
    op.add_column('users', sa.Column('exam_type', sa.String(length=20), nullable=True, comment='thpt | dgnl | dgtd'))
    op.add_column('users', sa.Column('exam_year', sa.Integer(), nullable=True, comment='Năm thi'))
    op.add_column('users', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Lần cập nhật học lực gần nhất'))
    op.add_column('users', sa.Column('session_id', sa.UUID(), nullable=True, comment='Phiên tạo ra DCP này'))
    op.add_column('users', sa.Column('score_R', sa.Float(), nullable=True, comment='Điểm Realistic (0–100)'))
    op.add_column('users', sa.Column('score_I', sa.Float(), nullable=True, comment='Điểm Investigative (0–100)'))
    op.add_column('users', sa.Column('score_A', sa.Float(), nullable=True, comment='Điểm Artistic (0–100)'))
    op.add_column('users', sa.Column('score_S', sa.Float(), nullable=True, comment='Điểm Social (0–100)'))
    op.add_column('users', sa.Column('score_E', sa.Float(), nullable=True, comment='Điểm Enterprising (0–100)'))
    op.add_column('users', sa.Column('score_C', sa.Float(), nullable=True, comment='Điểm Conventional (0–100)'))
    op.add_column('users', sa.Column('riasec_code', sa.String(length=3), nullable=True, comment='Mã Holland nổi trội, ví dụ: RI, RIA'))
    op.add_column('users', sa.Column('top_groups', postgresql.ARRAY(sa.String()), nullable=True, comment="Mảng nhóm nổi trội: ['R','I']"))
    op.add_column('users', sa.Column('confidence', sa.Float(), nullable=True, comment='Độ tin cậy kết quả (0.0–1.0)'))
    op.add_column('users', sa.Column('reasoning', sa.Text(), nullable=True, comment='Lý giải AI dựa trên bằng chứng hội thoại'))
    op.add_column('users', sa.Column('suggested_majors', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Danh sách nhóm ngành gợi ý + mô tả'))
    op.add_column('users', sa.Column('dcp_created_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Thời điểm tạo DCP'))
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               comment='Họ và tên đầy đủ',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               comment='Email đăng nhập',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Tài khoản còn hoạt động không',
               existing_nullable=True)
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.create_index(op.f('ix_users_student_id'), 'users', ['student_id'], unique=False)
    op.create_unique_constraint(None, 'users', ['session_id'])
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'id')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_student_id'), table_name='users')
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Tài khoản còn hoạt động không',
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Email đăng nhập',
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Họ và tên đầy đủ',
               existing_nullable=False)
    op.drop_column('users', 'dcp_created_at')
    op.drop_column('users', 'suggested_majors')
    op.drop_column('users', 'reasoning')
    op.drop_column('users', 'confidence')
    op.drop_column('users', 'top_groups')
    op.drop_column('users', 'riasec_code')
    op.drop_column('users', 'score_C')
    op.drop_column('users', 'score_E')
    op.drop_column('users', 'score_S')
    op.drop_column('users', 'score_A')
    op.drop_column('users', 'score_I')
    op.drop_column('users', 'score_R')
    op.drop_column('users', 'session_id')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'exam_year')
    op.drop_column('users', 'exam_type')
    op.drop_column('users', 'exam_scores')
    op.drop_column('users', 'grade_12_avg')
    op.drop_column('users', 'grade_11_avg')
    op.drop_column('users', 'grade_10_avg')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'target_province')
    op.drop_column('users', 'priority_group')
    op.drop_column('users', 'area_code')
    op.drop_column('users', 'province')
    op.drop_column('users', 'dob')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'student_id')
    # ### end Alembic commands ###
