from pydantic import BaseModel, Field


class SearchQueryModel(BaseModel):
    """
    Schema for the output generated by the Query Builder (LLM).
    """
    optimized_query: str = Field(
        ...,
        description="The main semantic search query optimized for pgvector."
    )
    target_countries: list[str] = Field(
        ...,
        description="List of specific countries extracted from the user profile."
    )
    target_majors: list[str] = Field(
        ...,
        description="List of specific majors to search for."
    )
    budget_limit_usd: float | None = Field(
        ...,
        description="The upper limit of tuition fee budget in USD (if mentioned)."
    )
    min_ielts: float | None = Field(
        ...,
        description="The user's IELTS score, serving as the minimum requirement."
    )
    keywords: list[str] = Field(
        ...,
        description="List of important keywords for filtering (e.g., 'scholarship', 'international students')."
    )
