"""init_admission_service

Revision ID: adb28d6ee962
Revises: 
Create Date: 2026-05-18 13:18:43.938580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'adb28d6ee962'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('university_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('logo', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.Integer(), server_default='0', nullable=False),
    sa.Column('name_universities', sa.String(length=200), nullable=False),
    sa.Column('name_majors', sa.String(length=200), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('type IN (0, 1)', name='ck_university_recommendations_type'),
    sa.PrimaryKeyConstraint('id'),
    schema='admission'
    )
    op.create_index(op.f('ix_admission_university_recommendations_name_majors'), 'university_recommendations', ['name_majors'], unique=False, schema='admission')
    op.create_index(op.f('ix_admission_university_recommendations_name_universities'), 'university_recommendations', ['name_universities'], unique=False, schema='admission')
    op.create_index(op.f('ix_admission_university_recommendations_student_id'), 'university_recommendations', ['student_id'], unique=False, schema='admission')
    op.create_index(op.f('ix_admission_university_recommendations_type'), 'university_recommendations', ['type'], unique=False, schema='admission')
    op.create_index('ix_university_recommendations_content_gin', 'university_recommendations', ['content'], unique=False, schema='admission', postgresql_using='gin')
    op.create_index('ix_university_recommendations_student_updated_at', 'university_recommendations', ['student_id', 'updated_at'], unique=False, schema='admission')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_university_recommendations_student_updated_at', table_name='university_recommendations', schema='admission')
    op.drop_index('ix_university_recommendations_content_gin', table_name='university_recommendations', schema='admission', postgresql_using='gin')
    op.drop_index(op.f('ix_admission_university_recommendations_type'), table_name='university_recommendations', schema='admission')
    op.drop_index(op.f('ix_admission_university_recommendations_student_id'), table_name='university_recommendations', schema='admission')
    op.drop_index(op.f('ix_admission_university_recommendations_name_universities'), table_name='university_recommendations', schema='admission')
    op.drop_index(op.f('ix_admission_university_recommendations_name_majors'), table_name='university_recommendations', schema='admission')
    op.drop_table('university_recommendations', schema='admission')
    # ### end Alembic commands ###
