"""add_university_models

Revision ID: c53fda54fdde
Revises: 
Create Date: 2026-05-16 05:34:23.326805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c53fda54fdde'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='admission'
    )
    op.create_index(op.f('ix_admission_universities_city'), 'universities', ['city'], unique=False, schema='admission')
    op.create_index(op.f('ix_admission_universities_country'), 'universities', ['country'], unique=False, schema='admission')
    op.create_index(op.f('ix_admission_universities_id'), 'universities', ['id'], unique=False, schema='admission')
    op.create_index(op.f('ix_admission_universities_name'), 'universities', ['name'], unique=False, schema='admission')
    op.create_table('university_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('university_name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('major_name', sa.String(), nullable=False),
    sa.Column('degree_level', sa.String(), nullable=True),
    sa.Column('tuition_fee', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('ielts_requirement', sa.Float(), nullable=True),
    sa.Column('gpa_requirement', sa.Float(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scholarship_info', sa.JSON(), nullable=True),
    sa.Column('career_outcomes', sa.JSON(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['admission.universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='admission'
    )
    op.create_index(op.f('ix_admission_university_programs_city'), 'university_programs', ['city'], unique=False, schema='admission')
    op.create_index(op.f('ix_admission_university_programs_country'), 'university_programs', ['country'], unique=False, schema='admission')
    op.create_index(op.f('ix_admission_university_programs_degree_level'), 'university_programs', ['degree_level'], unique=False, schema='admission')
    op.create_index(op.f('ix_admission_university_programs_id'), 'university_programs', ['id'], unique=False, schema='admission')
    op.create_index(op.f('ix_admission_university_programs_major_name'), 'university_programs', ['major_name'], unique=False, schema='admission')
    op.create_index(op.f('ix_admission_university_programs_university_name'), 'university_programs', ['university_name'], unique=False, schema='admission')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admission_university_programs_university_name'), table_name='university_programs', schema='admission')
    op.drop_index(op.f('ix_admission_university_programs_major_name'), table_name='university_programs', schema='admission')
    op.drop_index(op.f('ix_admission_university_programs_id'), table_name='university_programs', schema='admission')
    op.drop_index(op.f('ix_admission_university_programs_degree_level'), table_name='university_programs', schema='admission')
    op.drop_index(op.f('ix_admission_university_programs_country'), table_name='university_programs', schema='admission')
    op.drop_index(op.f('ix_admission_university_programs_city'), table_name='university_programs', schema='admission')
    op.drop_table('university_programs', schema='admission')
    op.drop_index(op.f('ix_admission_universities_name'), table_name='universities', schema='admission')
    op.drop_index(op.f('ix_admission_universities_id'), table_name='universities', schema='admission')
    op.drop_index(op.f('ix_admission_universities_country'), table_name='universities', schema='admission')
    op.drop_index(op.f('ix_admission_universities_city'), table_name='universities', schema='admission')
    op.drop_table('universities', schema='admission')
    # ### end Alembic commands ###
